[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[dependencies]
bootloader = "0.11.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
soso-abi = { path = "../crates/soso-abi" }
soso-update-core = { path = "../crates/soso-update-core", features = ["std"] }
soso-resize-core = { path = "../crates/soso-resize-core" }
sha2 = "0.10"
