fn main() {
    // Rotación de la consola fijada en el build (la Steam Deck la deduce sola;
    // esto es para corregir el sentido sin tocar código).
    println!("cargo:rerun-if-env-changed=SOSO_FB_ROT");
    gen_font12x12();
    if std::env::var("CARGO_FEATURE_LXDDE").is_ok() {
        let manifest_dir = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
        let root = manifest_dir.parent().unwrap();
        let lib_dir = root.join("target/lxdde");
        println!("cargo:rerun-if-changed={}", root.join("lxdde").display());
        println!("cargo:rerun-if-env-changed=SOSO_LXDDE");
        if lib_dir.join("liblxdde.a").exists() {
            println!("cargo:rustc-link-search=native={}", lib_dir.display());
            println!("cargo:rustc-link-lib=static=lxdde");
        } else {
            println!(
                "cargo:warning=lxdde: falta target/lxdde/liblxdde.a — ejecuta cargo xtask lx-build"
            );
        }
    }
}

/// Terminus 6×12 expandido a 12×12 (doble ancho) en compile-time.
fn gen_font12x12() {
    use embedded_bitmap_fonts::terminus::FONT_6x12;
    use embedded_graphics::geometry::{OriginDimensions, Point};
    use embedded_graphics::image::GetPixel;
    use embedded_graphics::pixelcolor::BinaryColor;
    use std::fmt::Write as _;
    use std::path::PathBuf;

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("font12x12.rs");
    let font = &FONT_6x12;
    let atlas = font.bitmap.size();
    let cpr = atlas.width / font.base_width();

    fn glyph_at(font: &embedded_bitmap_fonts::BitmapFont<'_>, cpr: u32, ch: char) -> [u16; 12] {
        let idx = font.glyph_mapping.index(ch) as u32;
        let row = idx / cpr;
        let cx = (idx - row * cpr) * font.base_width();
        let cy = row * font.base_height();
        let mut g = [0u16; 12];
        for gy in 0..12i32 {
            let mut narrow = 0u8;
            for gx in 0..6i32 {
                let p = font.bitmap.pixel(Point::new(cx as i32 + gx, cy as i32 + gy));
                if p == Some(BinaryColor::On) {
                    narrow |= 1 << gx;
                }
            }
            let mut wide = 0u16;
            for gx in 0..6 {
                if narrow & (1 << gx) != 0 {
                    wide |= 0b11 << (gx * 2);
                }
            }
            g[gy as usize] = wide;
        }
        g
    }

    // U+20AC (€): ausente en Terminus; expandir el glifo 8×8 propio.
    const EURO_8: [u8; 8] = [
        0b00111100, 0b01100110, 0b01100000, 0b00111100, 0b01100000, 0b01100110, 0b00111100,
        0b00000000,
    ];
    let mut euro = [0u16; 12];
    for (gy, row8) in EURO_8.iter().enumerate() {
        let mut wide = 0u16;
        for gx in 0..8 {
            if row8 & (1 << gx) != 0 {
                let a = gx * 12 / 8;
                let b = (gx + 1) * 12 / 8;
                for x in a..b.max(a + 1) {
                    wide |= 1 << x;
                }
            }
        }
        euro[gy] = wide;
    }

    let mut src = String::from("// @generated by kernel/build.rs — Terminus 6×12 → 12×12\n\n");
    write!(src, "pub const GLYPH_W: usize = 12;\n").unwrap();
    write!(src, "pub const GLYPH_H: usize = 12;\n\n").unwrap();
    write!(src, "pub const GLYPH_EURO: [u16; 12] = [").unwrap();
    for v in &euro {
        write!(src, "0x{v:03x}, ").unwrap();
    }
    writeln!(src, "];\n").unwrap();

    write!(src, "pub static BASIC: [[u16; 12]; 128] = [\n").unwrap();
    for cp in 0u32..128 {
        let ch = char::from_u32(cp).unwrap_or('?');
        let g = if (0x20..0x7f).contains(&cp) || cp == 0x7f {
            glyph_at(font, cpr, ch)
        } else {
            glyph_at(font, cpr, '?')
        };
        write!(src, "    // U+{cp:04X}\n    [").unwrap();
        for v in &g {
            write!(src, "0x{v:03x}, ").unwrap();
        }
        writeln!(src, "],").unwrap();
    }
    writeln!(src, "];\n").unwrap();

    write!(src, "pub static LATIN: [[u16; 12]; 96] = [\n").unwrap();
    for cp in 0xA0u32..=0xFF {
        let ch = char::from_u32(cp).unwrap_or('?');
        let g = glyph_at(font, cpr, ch);
        write!(src, "    // U+{cp:04X}\n    [").unwrap();
        for v in &g {
            write!(src, "0x{v:03x}, ").unwrap();
        }
        writeln!(src, "],").unwrap();
    }
    writeln!(src, "];").unwrap();

    write!(
        src,
        r#"pub fn row(cp: u16, gy: usize) -> u16 {{
    if gy >= GLYPH_H {{
        return 0;
    }}
    if cp == 0x20AC {{
        return GLYPH_EURO[gy];
    }}
    if cp < 0x80 {{
        let idx = cp as usize;
        if idx < BASIC.len() {{
            return BASIC[idx][gy];
        }}
    }} else if (0xA0..=0xFF).contains(&cp) {{
        let idx = (cp - 0xA0) as usize;
        if idx < LATIN.len() {{
            return LATIN[idx][gy];
        }}
    }}
    BASIC[b'?' as usize][gy]
}}
"#
    )
    .unwrap();

    std::fs::write(&out, src).expect("font12x12.rs");
    println!("cargo:rerun-if-changed=build.rs");
}
