[package]
name = "soso-wpa2"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"
description = "Supplicant WPA2-PSK/CCMP no_std para soso (iwlwifi)"

[dependencies]
sha1 = { version = "0.10", default-features = false }
hmac = { version = "0.12", default-features = false }
pbkdf2 = { version = "0.12", default-features = false, features = ["hmac"] }
aes = { version = "0.8", default-features = false }

